server:
  port: 8084

spring:
  application:
    name: medicalrecords-service

  cloud:
    eureka:
      client:
        fetchRegistry: true
        register-with-eureka: true
        serviceUrl:
          default-zone: http://localhost:8761/eureka/
      server:
        enable-self-preservation: true