services:
  # mysql
  mysqldb:
    image: mysql:8.4.0
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MYSQL_ROOT_PASSWORD=qqddqsqddqqdqdsqds
      - MYSQL_DATABASE=medilabo
    ports:
      - '3306:3306'  # Keep this for development
    volumes:
      - medilabo:/var/lib/mysql
    networks:
      - backend

  # mongo db
  mongo:
    image: mongo
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - '27017:27017'  # Keep this for development
    networks:
      - backend
    volumes:
      - medrecords:/var/lib/mongodb

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '9000:8081'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_URL=mongodb://root:admin@mongo:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongo
    networks:
      - backend
    volumes:
      - medrecords:/var/lib/mongodb

  #Services initiation
  eurekaserver:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - backend
      - frontend
    ports:
      - '8761:8761'

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - backend
      - frontend
    ports:
      - '5002:5002'

  volumekeeper:
    image: alpine:latest
    command: tail -f /dev/null
    networks:
      - backend
    volumes:
      - shared-libs:/libs

  shareddto:
    build:
      context: ./shareddto
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - backend
    volumes:
      - shared-libs:/libs
    command: tail -f /dev/null

  sharedinterface:
    build:
      context: ./sharedinterface
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - backend
    volumes:
      - shared-libs:/libs
    depends_on:
      - shareddto

  medicalrecordservice:
    build:
      context: ./medicalrecordservice
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - backend
    volumes:
      - shared-libs:/libs
    depends_on:
      - mongo
      - volumekeeper

  patientservice:
    build:
      context: ./patients
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - backend
    depends_on:
      - medicalrecordservice
      - mysqldb
    volumes:
      - shared-libs:/libs

  riskservice:
    build:
      context: ./riskservice
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - backend
    depends_on:
      - medicalrecordservice
      - patientservice
    volumes:
      - shared-libs:/libs

  frontendservice:
    build:
      context: ./frontendservice
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - backend
    volumes:
      - shared-libs:/libs
    depends_on:
      - medicalrecordservice
      - patientservice
      - riskservice

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

volumes:
  medrecords:
  medilabo:
  shared-libs:
    driver: local

