server:
  port: 8761

eureka:
  instance:
    hostname: eurekaserver
    preferIpAddress: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/