server:
  port: 8083

spring:
  application:
    name: gateway-service

  cloud:
    eureka:
      client:
        fetch-registry: true
        register-with-eureka: true
        serviceUrl:
          default-zone: http://localhost:8761/eureka/
      server:
        enable-self-preservation: false
    gateway:
      routes:
        - id: home-route
          uri: lb://frontendservice
          predicates:
            - Path=/home/**
        - id: patients-frontend-route
          uri: lb://frontendservice
          predicates:
            - Path=/patients
            - Method=GET
        - id: patients-service-route
          uri: lb://patientservice
          predicates:
            - Path=/patients/**
            - Method=GET,POST,PUT,DELETE
        - id: risk-assessment-route
          uri: lb://riskservice
          predicates:
            - Path=/patients/risk/**
            - Method=GET

    discovery:
      locator:
        enabled: true
  main:
    web-application-type: reactive

logging:
  level:
    org.springframework.cloud.gateway: DEBUG