server:
  port: 5002

spring:
  application:
    name: gateway-service

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/
  instance:
    preferIpAddress: true

  cloud:
    eureka:
      client:
        fetch-registry: true
        register-with-eureka: true
        serviceUrl:
          defaultZone: http://eurekaserver:8761/eureka/
      instance:
        preferIpAddress: true
      server:
        enable-self-preservation: false
    gateway:
      routes:
        - id: home-route
          uri: lb://frontendservice
          predicates:
            - Path=/home/**
        - id: patients-frontend-route
          uri: lb://frontendservice
          predicates:
            - Path=/patients, /patients/get/**
            - Method=GET
        - id: patients-service-route
          uri: lb://patientservice
          predicates:
            - Path=/patients/**
            - Method=GET,POST,PUT,DELETE
        - id: risk-assessment-route
          uri: lb://riskservice
          predicates:
            - Path=/patients/risk/**
            - Method=GET
        - id: eureka-server-route
          uri: http://eurekaserver:8761
          predicates:
            - Path=/eureka/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - RewritePath=/eureka/(?<segment>.*), /$\{segment}

    discovery:
      locator:
        enabled: true
  main:
    web-application-type: reactive

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG