server:
  port: 5002

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: home-route
          uri: lb://frontendservice
          predicates:
            - Path=/, /patients, /patients/get/**
            - Method=GET
        - id: frontend-route-update
          uri: lb://frontendservice
          predicates:
            - Path=/patients/update/**
            - Method=POST
        - id: frontend-route-delete
          uri: lb://frontendservice
          predicates:
            - Path=/patients/delete/**
            - Method=GET
        - id: patients-service-route
          uri: lb://patientservice
          predicates:
            - Path=/backend/patients/**
            - Method=GET,POST,PUT,DELETE
        - id: risk-assessment-route
          uri: lb://riskservice
          predicates:
            - Path=/patients/risk/**
            - Method=GET
        - id: eureka-server-route
          uri: http://eurekaserver:8761
          predicates:
            - Path=/eureka/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - RewritePath=/eureka/(?<segment>.*), /$\{segment}

    discovery:
      locator:
        enabled: true
  main:
    web-application-type: reactive

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/
  instance:
    preferIpAddress: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG