server:
  port: 8080

spring:
  application:
    name: patients-service

  datasource:
    url: jdbc:mysql://localhost:3306/medilabo
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    eureka:
      client:
        fetchRegistry: true
        register-with-eureka: true
        serviceUrl:
          default-zone: http://localhost:8761/eureka/
      server:
        enable-self-preservation: true