server:
  port: 8085

spring:
  main:
    web-application-type: reactive
  application:
    name: riskservice

  cloud:
    eureka:
      client:
        fetchRegistry: true
        register-with-eureka: true
        serviceUrl:
          default-zone: http://localhost:8761/eureka/
      server:
        enable-self-preservation: true

