server:
  port: 8081

spring:
  main:
    web-application-type: servlet
  application:
    name: frontendservice

  cloud:
    eureka:
      client:
        fetchRegistry: true
        register-with-eureka: true
        serviceUrl:
          default-zone: http://localhost:8761/eureka/
      server:
        enable-self-preservation: true