services:
  # mysql
  mysqldb:
    image: mysql:8.4.0
    #latest bad practice - https://www.augmentedmind.de/2022/05/15/docker-image-tag-best-practices/
    environment:
      - MYSQL_ROOT_PASSWORD=qqddqsqddqqdqdsqds
      - MYSQL_DATABASE=medilabo
    ports:
      - '3306:3306'
    volumes:
      - medilabo:/var/lib/mysql

  # mongo db
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - '27017:27017'

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '9000:8081'  # Corrected port mapping
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_URL=mongodb://root:admin@mongo:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongo

volumes:
  medilabo:

  #https://medium.com/@chrischuck35/how-to-create-a-mysql-instance-with-docker-compose-1598f3cc1bee
  #https://hub:docker:com/_/mongo:
  #https://www:youtube:com/watch?v=QumOvEDMQ34: