server:
  port: 8084

spring:
  application:
    name: medicalrecordservice

  cloud:
    eureka:
      client:
        fetchRegistry: true
        register-with-eureka: true
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/
      server:
        enable-self-preservation: true

  data:
    mongodb:
      authentication-database: admin
      host: localhost
      port: 27017
      database: medicalrecords
      username: root
      password: admin